package src;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Properties;
import javax.swing.BorderFactory;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

public class MainFrame extends javax.swing.JFrame {
	
	private static final long serialVersionUID = 1L;
    JDatePickerImpl datePicker2;
    JDatePickerImpl datePicker;
    int xMouse;
    int yMouse;
    
    public MainFrame() {
        initComponents();
        adjustFrame();
        calendar();       
    }
    
    private void adjustFrame(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    private void calendar(){
        UtilDateModel model = new UtilDateModel();
        UtilDateModel model2 = new UtilDateModel();

        Properties p = new Properties();
        p.put("text.today", "Today");
        p.put("text.month", "Month");
        p.put("text.year", "Year");
        JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
        datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
        JDatePanelImpl datePanel2 = new JDatePanelImpl(model2, p);
        datePicker2 = new JDatePickerImpl(datePanel2, new DateLabelFormatter());
               
    
        datePicker.setBounds(0,0,120,30);
        datePicker2.setBounds(0,0,120,30);
        jDepartingCalendar.add(datePicker);
        jReturningCalendar.add(datePicker2);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jBackground = new javax.swing.JPanel();
        jMenu = new javax.swing.JPanel();
        jExit = new javax.swing.JLabel();
        jInstruction = new javax.swing.JLabel();
        jAbout = new javax.swing.JLabel();
        jContact = new javax.swing.JLabel();
        jFlight = new javax.swing.JLabel();
        jHotel = new javax.swing.JLabel();
        jTours = new javax.swing.JLabel();
        jTabArea = new javax.swing.JPanel();
        jSearch = new javax.swing.JPanel();
        jDepartureLabel = new javax.swing.JLabel();
        jLocationLabel = new javax.swing.JLabel();
        jTravelerLabel = new javax.swing.JLabel();
        jBoxDeparture = new javax.swing.JComboBox<>();
        jBoxLocation = new javax.swing.JComboBox<>();
        jTravelerSpinner = new javax.swing.JSpinner();
        jDepartingLabel = new javax.swing.JLabel();
        jReturningLabel = new javax.swing.JLabel();
        jDepartingCalendar = new javax.swing.JPanel();
        jReturningCalendar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jHotelSelect = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToursSelect = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jBackground.setBackground(new java.awt.Color(255, 255, 255));
        jBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu.setBackground(new java.awt.Color(51, 51, 51));
        jMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jMenuMouseDragged(evt);
            }
        });
        jMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuMousePressed(evt);
            }
        });

        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Multiply_64px_1.png"))); // NOI18N
        jExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jExitMouseClicked(evt);
            }
        });

        jInstruction.setBackground(new java.awt.Color(255, 255, 255));
        jInstruction.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jInstruction.setForeground(new java.awt.Color(255, 255, 255));
        jInstruction.setText("Instruction");

        jAbout.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jAbout.setForeground(new java.awt.Color(255, 255, 255));
        jAbout.setText("About");

        jContact.setBackground(new java.awt.Color(255, 255, 255));
        jContact.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jContact.setForeground(new java.awt.Color(255, 255, 255));
        jContact.setText("Contact");

        javax.swing.GroupLayout jMenuLayout = new javax.swing.GroupLayout(jMenu);
        jMenu.setLayout(jMenuLayout);
        jMenuLayout.setHorizontalGroup(
            jMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMenuLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jContact, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExit)
                .addGap(27, 27, 27))
        );
        jMenuLayout.setVerticalGroup(
            jMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMenuLayout.createSequentialGroup()
                .addGroup(jMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jExit))
                    .addGroup(jMenuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jContact)
                            .addComponent(jAbout)
                            .addComponent(jInstruction))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jFlight.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jFlight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Flight.png"))); // NOI18N
        jFlight.setText("Flight");
        jFlight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFlightMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jFlightMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jFlightMouseExited(evt);
            }
        });

        jHotel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jHotel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/5 Star Hotel_50px.png"))); // NOI18N
        jHotel.setText("Hotel");
        jHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jHotelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jHotelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jHotelMouseExited(evt);
            }
        });

        jTours.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jTours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Tour Bus_48px.png"))); // NOI18N
        jTours.setText("Day Tours");
        jTours.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToursMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jToursMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jToursMouseExited(evt);
            }
        });

        jTabArea.setBackground(new java.awt.Color(255, 255, 255));
        jTabArea.setLayout(new java.awt.CardLayout());

        jSearch.setBackground(new java.awt.Color(255, 255, 255));

        jDepartureLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jDepartureLabel.setText("Departure");

        jLocationLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLocationLabel.setText("Location");

        jTravelerLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTravelerLabel.setText("Traveler");

        jBoxDeparture.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jBoxDeparture.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBoxLocation.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jBoxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTravelerSpinner.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jTravelerSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jDepartingLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jDepartingLabel.setText("Departing");

        jReturningLabel.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jReturningLabel.setText("Returning");

        jDepartingCalendar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDepartingCalendarLayout = new javax.swing.GroupLayout(jDepartingCalendar);
        jDepartingCalendar.setLayout(jDepartingCalendarLayout);
        jDepartingCalendarLayout.setHorizontalGroup(
            jDepartingCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );
        jDepartingCalendarLayout.setVerticalGroup(
            jDepartingCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jReturningCalendar.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jReturningCalendarLayout = new javax.swing.GroupLayout(jReturningCalendar);
        jReturningCalendar.setLayout(jReturningCalendarLayout);
        jReturningCalendarLayout.setHorizontalGroup(
            jReturningCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jReturningCalendarLayout.setVerticalGroup(
            jReturningCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Right_48px.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jSearchLayout = new javax.swing.GroupLayout(jSearch);
        jSearch.setLayout(jSearchLayout);
        jSearchLayout.setHorizontalGroup(
            jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchLayout.createSequentialGroup()
                .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSearchLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDepartureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBoxDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jSearchLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDepartingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDepartingCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jSearchLayout.createSequentialGroup()
                        .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jReturningLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jReturningCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jSearchLayout.createSequentialGroup()
                        .addComponent(jLocationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTravelerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(jSearchLayout.createSequentialGroup()
                        .addComponent(jBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(jTravelerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(128, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(93, 93, 93))
        );
        jSearchLayout.setVerticalGroup(
            jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSearchLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDepartureLabel)
                    .addComponent(jLocationLabel)
                    .addComponent(jTravelerLabel))
                .addGap(18, 18, 18)
                .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoxDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTravelerSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDepartingLabel)
                    .addComponent(jReturningLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDepartingCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jReturningCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37))
        );

        jTabArea.add(jSearch, "card2");

        jHotelSelect.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Hotel design something here....");

        javax.swing.GroupLayout jHotelSelectLayout = new javax.swing.GroupLayout(jHotelSelect);
        jHotelSelect.setLayout(jHotelSelectLayout);
        jHotelSelectLayout.setHorizontalGroup(
            jHotelSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHotelSelectLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        jHotelSelectLayout.setVerticalGroup(
            jHotelSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHotelSelectLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jTabArea.add(jHotelSelect, "card3");

        jToursSelect.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel3.setText("Tours design something here....");

        javax.swing.GroupLayout jToursSelectLayout = new javax.swing.GroupLayout(jToursSelect);
        jToursSelect.setLayout(jToursSelectLayout);
        jToursSelectLayout.setHorizontalGroup(
            jToursSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jToursSelectLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jToursSelectLayout.setVerticalGroup(
            jToursSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jToursSelectLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabArea.add(jToursSelect, "card4");

        javax.swing.GroupLayout jBackgroundLayout = new javax.swing.GroupLayout(jBackground);
        jBackground.setLayout(jBackgroundLayout);
        jBackgroundLayout.setHorizontalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jBackgroundLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBackgroundLayout.createSequentialGroup()
                        .addComponent(jTabArea, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(jBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jTours, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        jBackgroundLayout.setVerticalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBackgroundLayout.createSequentialGroup()
                .addComponent(jMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTours, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabArea, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jExitMouseClicked(java.awt.event.MouseEvent evt) {                                   
        System.exit(0);
    }                                  

    private void jMenuMouseDragged(java.awt.event.MouseEvent evt) {                                   
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }                                  

    private void jMenuMousePressed(java.awt.event.MouseEvent evt) {                                   
        xMouse= evt.getX();
        yMouse= evt.getY();
    }                                  

    private void jFlightMouseEntered(java.awt.event.MouseEvent evt) {                                     
        jFlight.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
    }                                    

    private void jFlightMouseExited(java.awt.event.MouseEvent evt) {                                    
        jFlight.setBorder(BorderFactory.createEmptyBorder());
    }                                   

    private void jHotelMouseEntered(java.awt.event.MouseEvent evt) {                                    
        jHotel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
    }                                   

    private void jHotelMouseExited(java.awt.event.MouseEvent evt) {                                   
        jHotel.setBorder(BorderFactory.createEmptyBorder());
    }                                  

    private void jToursMouseEntered(java.awt.event.MouseEvent evt) {                                    
        jTours.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
    }                                   

    private void jToursMouseExited(java.awt.event.MouseEvent evt) {                                   
        jTours.setBorder(BorderFactory.createEmptyBorder());
    }                                  

    private void jFlightMouseClicked(java.awt.event.MouseEvent evt) {                                     
        //Removing old panel
        jTabArea.removeAll();
        jTabArea.repaint();
        jTabArea.validate();
        //Adding new one
        jTabArea.add(jSearch);
        jTabArea.repaint();
        jTabArea.validate();
        
    }                                    

    private void jHotelMouseClicked(java.awt.event.MouseEvent evt) {                                    
        //Removing old panel
        jTabArea.removeAll();
        jTabArea.repaint();
        jTabArea.validate();
        //Adding new one
        jTabArea.add(jHotelSelect);
        jTabArea.repaint();
        jTabArea.validate();
    }                                   

    private void jToursMouseClicked(java.awt.event.MouseEvent evt) {                                    
        jTabArea.removeAll();
        jTabArea.repaint();
        jTabArea.validate();
        //Adding new one
        jTabArea.add(jToursSelect);
        jTabArea.repaint();
        jTabArea.validate();
    }                                   

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        FlightSelection s = new FlightSelection(this, true);
        s.setVisible(true);
    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jAbout;
    private javax.swing.JPanel jBackground;
    private javax.swing.JComboBox<String> jBoxDeparture;
    private javax.swing.JComboBox<String> jBoxLocation;
    private javax.swing.JLabel jContact;
    private javax.swing.JPanel jDepartingCalendar;
    private javax.swing.JLabel jDepartingLabel;
    private javax.swing.JLabel jDepartureLabel;
    private javax.swing.JLabel jExit;
    private javax.swing.JLabel jFlight;
    private javax.swing.JLabel jHotel;
    private javax.swing.JPanel jHotelSelect;
    private javax.swing.JLabel jInstruction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLocationLabel;
    private javax.swing.JPanel jMenu;
    private javax.swing.JPanel jReturningCalendar;
    private javax.swing.JLabel jReturningLabel;
    private javax.swing.JPanel jSearch;
    private javax.swing.JPanel jTabArea;
    private javax.swing.JLabel jTours;
    private javax.swing.JPanel jToursSelect;
    private javax.swing.JLabel jTravelerLabel;
    private javax.swing.JSpinner jTravelerSpinner;
    // End of variables declaration                   
}

